name: "Setup C++"

on:
  push:
    branches:
      - main

env:
  FORMAT_FILE: README.md

jobs:
  test:
    name: 'Validate links'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate all links from README.md
        run: bash main.sh
